sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - 4
  - 5
  - 6
before_install:
  - npm i -g npm@^2.0.0
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start &"
  - "npm i webdriver-manager && ./node_modules/.bin/webdriver-manager update && ./node_modules/.bin/webdriver-manager start"
before_script:
  - npm prune
  - 'curl -Lo travis_after_all.py https://git.io/vLSON'
after_success:
  - python travis_after_all.py
  - export $(cat .to_export_back)
  - npm run semantic-release
script: PROTRACTOR_FLAKE_LOG_LEVEL=debug npm test
